/**
 * 投稿関連のSQLite操作
 */

import { queryOne, queryAll, execute, executeBatch } from './client';
import type { PostRow, ImageRow } from '@/shared/types/database.types';
import type { UUID } from '@/shared/types';

// ===============================
// 投稿取得
// ===============================

/**
 * IDで投稿を取得
 */
export function getPostById(postId: UUID): PostRow | null {
  return queryOne<PostRow>('SELECT * FROM posts WHERE id = ?;', [postId]);
}

/**
 * ユーザーの全投稿を取得
 */
export function getPostsByUserId(userId: UUID): PostRow[] {
  return queryAll<PostRow>(
    'SELECT * FROM posts WHERE user_id = ? ORDER BY created_at DESC;',
    [userId]
  );
}

/**
 * 訪問記録に紐づく投稿を取得
 */
export function getPostsByVisitId(visitId: UUID): PostRow[] {
  return queryAll<PostRow>(
    'SELECT * FROM posts WHERE visit_id = ? ORDER BY created_at DESC;',
    [visitId]
  );
}

/**
 * 投稿をページネーションで取得
 */
export function getPostsPaginated(
  userId: UUID,
  limit: number,
  offset: number
): PostRow[] {
  return queryAll<PostRow>(
    `
    SELECT * FROM posts
    WHERE user_id = ?
    ORDER BY created_at DESC
    LIMIT ? OFFSET ?;
    `,
    [userId, limit, offset]
  );
}

/**
 * タイムライン用投稿取得（全ユーザー、フレンド機能実装時に拡張）
 */
export function getTimelinePosts(limit: number, offset: number): PostRow[] {
  return queryAll<PostRow>(
    `
    SELECT * FROM posts
    WHERE is_draft = 0
    ORDER BY created_at DESC
    LIMIT ? OFFSET ?;
    `,
    [limit, offset]
  );
}

/**
 * 自動生成投稿を取得
 */
export function getAutoGeneratedPostByVisitId(visitId: UUID): PostRow | null {
  return queryOne<PostRow>(
    'SELECT * FROM posts WHERE visit_id = ? AND is_auto_generated = 1;',
    [visitId]
  );
}

// ===============================
// 投稿作成・更新
// ===============================

/**
 * 投稿を作成
 */
export function insertPost(post: PostRow): void {
  execute(
    `
    INSERT INTO posts (
      id, user_id, content, machi_id, visit_id, is_auto_generated,
      is_draft, likes_count, comments_count, created_at, updated_at,
      synced_at, is_synced
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
    `,
    [
      post.id,
      post.user_id,
      post.content,
      post.machi_id,
      post.visit_id,
      post.is_auto_generated,
      post.is_draft,
      post.likes_count,
      post.comments_count,
      post.created_at,
      post.updated_at,
      post.synced_at,
      post.is_synced,
    ]
  );
}

/**
 * 投稿を更新
 */
export function updatePost(
  postId: UUID,
  data: {
    content?: string;
    machi_id?: string | null;
    is_draft?: 0 | 1;
    likes_count?: number;
    comments_count?: number;
    synced_at?: string | null;
    is_synced?: 0 | 1;
    updated_at: string;
  }
): void {
  const fields: string[] = [];
  const values: any[] = [];

  if (data.content !== undefined) {
    fields.push('content = ?');
    values.push(data.content);
  }

  if (data.machi_id !== undefined) {
    fields.push('machi_id = ?');
    values.push(data.machi_id);
  }

  if (data.is_draft !== undefined) {
    fields.push('is_draft = ?');
    values.push(data.is_draft);
  }

  if (data.likes_count !== undefined) {
    fields.push('likes_count = ?');
    values.push(data.likes_count);
  }

  if (data.comments_count !== undefined) {
    fields.push('comments_count = ?');
    values.push(data.comments_count);
  }

  if (data.synced_at !== undefined) {
    fields.push('synced_at = ?');
    values.push(data.synced_at);
  }

  if (data.is_synced !== undefined) {
    fields.push('is_synced = ?');
    values.push(data.is_synced);
  }

  fields.push('updated_at = ?');
  values.push(data.updated_at);

  values.push(postId);

  execute(`UPDATE posts SET ${fields.join(', ')} WHERE id = ?;`, values);
}

// ===============================
// 投稿削除
// ===============================

/**
 * 投稿を削除
 */
export function deletePost(postId: UUID): void {
  execute('DELETE FROM posts WHERE id = ?;', [postId]);
}

/**
 * 訪問記録に紐づく全投稿を削除
 */
export function deletePostsByVisitId(visitId: UUID): void {
  execute('DELETE FROM posts WHERE visit_id = ?;', [visitId]);
}

/**
 * ユーザーの全投稿を削除
 */
export function deleteAllPostsByUser(userId: UUID): void {
  execute('DELETE FROM posts WHERE user_id = ?;', [userId]);
}

// ===============================
// 投稿画像操作
// ===============================

/**
 * 投稿の画像を取得
 */
export function getPostImages(postId: UUID): ImageRow[] {
  return queryAll<ImageRow>(
    `
    SELECT * FROM images
    WHERE post_id = ?
    ORDER BY order_index;
    `,
    [postId]
  );
}

/**
 * 投稿画像を挿入
 */
export function insertPostImage(image: ImageRow): void {
  execute(
    `
    INSERT INTO images (
      id, post_id, local_path, cloud_path, width, height,
      file_size, order_index, created_at, synced_at, is_synced
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
    `,
    [
      image.id,
      image.post_id,
      image.local_path,
      image.cloud_path,
      image.width,
      image.height,
      image.file_size,
      image.order_index,
      image.created_at,
      image.synced_at,
      image.is_synced,
    ]
  );
}

/**
 * 複数の投稿画像を一括挿入
 */
export function bulkInsertPostImages(images: ImageRow[]): void {
  const statements = images.map((image) => ({
    sql: `
      INSERT INTO images (
        id, post_id, local_path, cloud_path, width, height,
        file_size, order_index, created_at, synced_at, is_synced
      )
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
    `,
    params: [
      image.id,
      image.post_id,
      image.local_path,
      image.cloud_path,
      image.width,
      image.height,
      image.file_size,
      image.order_index,
      image.created_at,
      image.synced_at,
      image.is_synced,
    ],
  }));

  executeBatch(statements);
}

/**
 * 投稿画像を削除
 */
export function deletePostImage(imageId: UUID): void {
  execute('DELETE FROM images WHERE id = ?;', [imageId]);
}

/**
 * 投稿の全画像を削除
 */
export function deleteAllPostImages(postId: UUID): void {
  execute('DELETE FROM images WHERE post_id = ?;', [postId]);
}

// ===============================
// 統計情報
// ===============================

/**
 * ユーザーの総投稿数を取得
 */
export function getTotalPostCount(userId: UUID): number {
  const result = queryOne<{ count: number }>(
    'SELECT COUNT(*) as count FROM posts WHERE user_id = ?;',
    [userId]
  );
  return result?.count ?? 0;
}

/**
 * 月別投稿数を取得
 */
export function getMonthlyPostCount(
  userId: UUID,
  year: number,
  month: number
): number {
  const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
  const endDate = `${year}-${String(month + 1).padStart(2, '0')}-01`;

  const result = queryOne<{ count: number }>(
    `
    SELECT COUNT(*) as count
    FROM posts
    WHERE user_id = ?
      AND created_at >= ?
      AND created_at < ?;
    `,
    [userId, startDate, endDate]
  );

  return result?.count ?? 0;
}
