/**
 * 訪問記録を作成するhook
 */

import { useMutation } from '@tanstack/react-query';
import { invalidateVisits, invalidatePosts } from '@/shared/api/query-client';
import {
  getVisitByUserAndMachi,
  insertVisit,
  incrementVisitCount,
  getMachiById,
  insertPost,
} from '@/shared/api/sqlite';
import {
  createVisitData,
  validateCreateVisitParams,
} from '../model';
import { createPostData, createAutoPostContent } from '@/entities/post/model';
import type { CreateVisitParams } from '../model/types';

/**
 * 訪問記録を作成または更新（自動投稿も作成）
 */
export function useCreateVisit() {
  return useMutation({
    mutationFn: async (params: CreateVisitParams) => {
      // バリデーション
      const validation = validateCreateVisitParams(params);
      if (!validation.valid) {
        throw new Error(validation.error);
      }

      // 街情報を取得
      const machi = getMachiById(params.stationId);
      if (!machi) {
        throw new Error('街が見つかりません');
      }

      // 既存の訪問記録をチェック
      const existingVisit = getVisitByUserAndMachi(
        params.userId,
        params.stationId
      );

      let visitId: string;
      let visitCount: number;

      if (existingVisit) {
        // 既存の場合は訪問回数をインクリメント
        incrementVisitCount(existingVisit.id, params.visitedAt || new Date().toISOString());
        visitId = existingVisit.id;
        visitCount = (existingVisit.visit_count ?? 0) + 1;
      } else {
        // 新規作成
        const newVisit = createVisitData(params);
        insertVisit(newVisit);
        visitId = newVisit.id;
        visitCount = 1;
      }

      // 自動投稿を作成
      const autoPostContent = createAutoPostContent(machi.name, visitCount);
      const autoPost = createPostData({
        userId: params.userId,
        content: autoPostContent,
        stationId: params.stationId,
        visitId: visitId,
        isAutoGenerated: true,
        isDraft: false,
      });
      insertPost(autoPost);

      return visitId;
    },
    onSuccess: () => {
      // 訪問記録と投稿のキャッシュを無効化
      invalidateVisits();
      invalidatePosts();
    },
  });
}
