/**
 * Post ビジネスロジック
 */

import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';
import type { PostRow } from '@/shared/types/database.types';
import type { CreatePostParams } from './types';

// ===============================
// 投稿作成
// ===============================

/**
 * 新規投稿データを作成
 */
export function createPostData(params: CreatePostParams): PostRow {
  const now = new Date().toISOString();

  return {
    id: uuidv4(),
    user_id: params.userId,
    content: params.content,
    machi_id: params.stationId || null,
    visit_id: params.visitId || null,
    is_auto_generated: params.isAutoGenerated ? 1 : 0,
    is_draft: params.isDraft ? 1 : 0,
    likes_count: 0,
    comments_count: 0,
    created_at: now,
    updated_at: now,
    synced_at: null,
    is_synced: 0,
  };
}

/**
 * 自動生成投稿のテキストを作成
 */
export function createAutoPostContent(
  stationName: string,
  visitCount: number
): string {
  return `${stationName}チェックイン（${visitCount}回目の訪問）`;
}

// ===============================
// バリデーション
// ===============================

/**
 * 投稿作成パラメータのバリデーション
 */
export function validateCreatePostParams(
  params: CreatePostParams
): { valid: boolean; error?: string } {
  if (!params.userId || params.userId.trim() === '') {
    return { valid: false, error: 'ユーザーIDが必要です' };
  }

  if (!params.content || params.content.trim() === '') {
    return { valid: false, error: '投稿内容が必要です' };
  }

  if (params.content.length > 2000) {
    return { valid: false, error: '投稿内容は2000文字以内にしてください' };
  }

  if (params.images && params.images.length > 4) {
    return { valid: false, error: '画像は4枚まで添付できます' };
  }

  return { valid: true };
}

// ===============================
// フォーマット
// ===============================

/**
 * 投稿日時を日本語フォーマットで取得
 */
export function formatPostDate(createdAt: string): string {
  const date = new Date(createdAt);
  return new Intl.DateTimeFormat('ja-JP', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

/**
 * 投稿日時を相対時間で取得
 */
export function getRelativePostTime(createdAt: string): string {
  const now = new Date();
  const posted = new Date(createdAt);
  const diffInMs = now.getTime() - posted.getTime();
  const diffInMinutes = Math.floor(diffInMs / (1000 * 60));
  const diffInHours = Math.floor(diffInMs / (1000 * 60 * 60));
  const diffInDays = Math.floor(diffInMs / (1000 * 60 * 60 * 24));

  if (diffInMinutes < 1) return 'たった今';
  if (diffInMinutes < 60) return `${diffInMinutes}分前`;
  if (diffInHours < 24) return `${diffInHours}時間前`;
  if (diffInDays < 7) return `${diffInDays}日前`;
  return formatPostDate(createdAt);
}

// ===============================
// ソート・フィルタ
// ===============================

/**
 * 投稿を日付でソート（新しい順）
 */
export function sortPostsByDate(posts: PostRow[]): PostRow[] {
  return [...posts].sort(
    (a, b) =>
      new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );
}

/**
 * 下書き投稿のみフィルタ
 */
export function filterDraftPosts(posts: PostRow[]): PostRow[] {
  return posts.filter((post) => post.is_draft === 1);
}

/**
 * 公開済み投稿のみフィルタ
 */
export function filterPublishedPosts(posts: PostRow[]): PostRow[] {
  return posts.filter((post) => post.is_draft === 0);
}

/**
 * 自動生成投稿のみフィルタ
 */
export function filterAutoGeneratedPosts(posts: PostRow[]): PostRow[] {
  return posts.filter((post) => post.is_auto_generated === 1);
}
