/**
 * Post エンティティ型定義
 */

import type { PostRow, ImageRow } from '@/shared/types/database.types';

// ===============================
// Domain Types
// ===============================

/**
 * 画像付き投稿
 */
export interface PostWithImages extends PostRow {
  images: ImageRow[];
}

/**
 * 投稿作成パラメータ
 */
export interface CreatePostParams {
  userId: string;
  content: string;
  stationId?: string;
  visitId?: string;
  isAutoGenerated?: boolean;
  isDraft?: boolean;
  images?: string[]; // 画像URI配列
}

/**
 * 投稿更新パラメータ
 */
export interface UpdatePostParams {
  postId: string;
  content?: string;
  stationId?: string | null;
  isDraft?: boolean;
}

/**
 * 画像アップロードパラメータ
 */
export interface UploadPostImagesParams {
  postId: string;
  imageUris: string[];
}
