/**
 * Style Dictionary Configuration
 *
 * デザイントークンを各プラットフォーム用に変換する設定
 * - Mobile: TypeScript + Tailwind theme object
 * - Web: CSS Variables
 * - Storybook: JSON (ドキュメント用)
 */

import StyleDictionary from 'style-dictionary';

// Mobile用 TypeScript format
StyleDictionary.registerFormat({
  name: 'typescript/mobile-tokens',
  format: ({ dictionary }) => {
    const tokens = {};

    dictionary.allTokens.forEach(token => {
      const path = token.path;
      let current = tokens;

      for (let i = 0; i < path.length - 1; i++) {
        const key = path[i];
        if (!current[key]) {
          current[key] = {};
        }
        current = current[key];
      }

      // value がオブジェクトの場合（参照解決済み）は value.value を取得
      const value = typeof token.value === 'object' && token.value?.value
        ? token.value.value
        : token.value;
      current[path[path.length - 1]] = value;
    });

    return `/**
 * Design Tokens - Auto-generated by Style Dictionary
 * Do not edit directly
 */

export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type Tokens = typeof tokens;
`;
  },
});

// Tailwind theme format
StyleDictionary.registerFormat({
  name: 'javascript/tailwind-theme',
  format: ({ dictionary }) => {
    const colors = {};

    dictionary.allTokens.forEach(token => {
      const path = token.path;
      // color で始まるトークンのみ、かつ値が文字列（カラーコード）のもの
      if (path[0] !== 'color') return;

      // value がオブジェクトの場合（参照解決済み）は value.value を取得
      let value = typeof token.value === 'object' && token.value?.value
        ? token.value.value
        : token.value;

      // 文字列でないもの（boolean等）はスキップ
      if (typeof value !== 'string') return;
      // # で始まるか transparent のみ
      if (!value.startsWith('#') && value !== 'transparent') return;

      let current = colors;

      for (let i = 1; i < path.length - 1; i++) { // Skip 'color' prefix
        const key = path[i];
        if (!current[key]) {
          current[key] = {};
        }
        current = current[key];
      }

      const lastKey = path[path.length - 1];
      current[lastKey] = value;
    });

    return `/**
 * Tailwind Theme Colors - Auto-generated by Style Dictionary
 * Do not edit directly
 */

module.exports = {
  colors: ${JSON.stringify(colors, null, 2)}
};
`;
  },
});

// CSS Variables format (Web用)
StyleDictionary.registerFormat({
  name: 'css/variables-web',
  format: ({ dictionary }) => {
    const lightVars = [];
    const darkVars = [];

    dictionary.allTokens.forEach(token => {
      const path = token.path;

      // value がオブジェクトの場合（参照解決済み）は value.value を取得
      let value = typeof token.value === 'object' && token.value?.value
        ? token.value.value
        : token.value;

      // 文字列でないもの（boolean等）はスキップ
      if (typeof value !== 'string') return;
      // # で始まるか transparent のみ
      if (!value.startsWith('#') && value !== 'transparent') return;

      // web.light.* と web.dark.* を分離
      if (path.includes('web')) {
        if (path.includes('light')) {
          const varName = path.slice(path.indexOf('light') + 1).join('-');
          lightVars.push(`  --${varName}: ${value};`);
        } else if (path.includes('dark')) {
          const varName = path.slice(path.indexOf('dark') + 1).join('-');
          darkVars.push(`  --${varName}: ${value};`);
        }
      }
    });

    return `/**
 * CSS Variables - Auto-generated by Style Dictionary
 * Do not edit directly
 */

@layer base {
  :root {
${lightVars.join('\n')}
  }

  .dark {
${darkVars.join('\n')}
  }
}
`;
  },
});

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    // Mobile (React Native + TypeScript)
    mobile: {
      transformGroup: 'js',
      buildPath: 'build/mobile/',
      files: [
        {
          destination: 'tokens.js',
          format: 'typescript/mobile-tokens',
        },
        {
          destination: 'tailwind-theme.js',
          format: 'javascript/tailwind-theme',
        },
      ],
    },

    // Web (CSS Variables)
    web: {
      transformGroup: 'css',
      buildPath: 'build/web/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables-web',
        },
      ],
    },

    // Storybook (JSON for documentation)
    storybook: {
      transformGroup: 'js',
      buildPath: 'build/storybook/',
      files: [
        {
          destination: 'tokens.json',
          format: 'json/nested',
        },
      ],
    },
  },
};
